### ISSUE TITLE
Weapon reload issue with the kick plugin

### ISSUE THREAD

**Issue by neguma** [Neyami/Various-Plugins#1]
hello Nero :) 

i noticed that if you do the kick while you're reloading a weapon, said weapon bugs out and not only the reload doesn't complete (which is logical), but the ammo will get stuck at 0 and you won't be able to reload anymore unless you swap weapons. it is just after swapping weapons that you'll be able to reload the one that got bugged with the kick.

is this fixable? thank you very much.

**Comment by Neyami** [comment]
Not really, the best I can do is prevent kicking while reloading 😅

**Comment by neguma** [comment]
> Not really, the best I can do is prevent kicking while reloading 😅

Ah, understood! well, people in my server better learn to deal with it. thank you Nero 😄
